### ISSUE TITLE
PyChatGPT no longer maintained and doesn't work

### ISSUE THREAD

**Issue by acheong08** [eon01/awesome-chatgpt#24]
![image](https://user-images.githubusercontent.com/36258159/231346012-1c05e6e0-b7b1-4c56-aac8-ed77559910c7.png)

https://github.com/rawandahmad698/PyChatGPT

https://github.com/eon01/awesome-chatgpt/blob/8e1c210b6bb9f631378ef55f65a91bb68bfe0d74/README.md?plain=1#L128

**Comment by eon01** [comment]
Thanks for letting me know. I added "Current State: Not maintained" after the description of the project.
