### ISSUE TITLE
New entries

### ISSUE THREAD

**Issue by momobobe** [eon01/awesome-chatgpt#3]
Request to add:

[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api): Node.js client for the unofficial ChatGPT API. 🔥
[node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api): A ChatGPT implementation with support for Bing's GPT-4 version of ChatGPT, plus the official ChatGPT model via OpenAI's API. Available as a Node.js module, REST API server, and CLI app.
[chatgpt_api_dart](https://github.com/MisterJimson/chatgpt_api_dart): Dart client for the unofficial ChatGPT API
🇨🇳 [chatgpt-web-api](https://github.com/swordintent/chatgpt-web-api): A Java Version ChatGPT SDK
🇨🇳 [chatgpt-java](https://github.com/PlexPt/chatgpt-java): ChatGPT Java SDK. Lightweight package for interacting with ChatGPT's API by OpenAI. Uses reverse engineered official API.
🇨🇳 [nonebot2](https://github.com/nonebot/nonebot2): Asynchronous multi-platform chatbot framework written in Python
[ChatGPT-Official](https://github.com/PawanOsman/ChatGPT-Official): ChatGPT Client using official OpenAI API 
[chatgpt-io](https://github.com/PawanOsman/chatgpt-io): ChatGPT Client API, Blazing Fast, without using browser
[PyGPT](https://github.com/PawanOsman/PyGPT): Python implementation of Unofficial ChatGPT Client
[ChatGPT.Net](https://github.com/PawanOsman/ChatGPT.Net): Unofficial .Net Client for ChatGPT
[chatgpt-api-wrapper](https://github.com/timkmecl/chatgpt-api-wrapper): Node.js wrapper for connecting to ChatGPT using official OpenAI API

**Comment by eon01** [comment]
Awesome! Thanks. Please open a pull request and I'll accept it :-)

**Comment by eon01** [comment]
FYI: I added your links. Thanks.
