### ISSUE TITLE
ChatGPT client for all platforms, OpenAI library for Delphi

### ISSUE THREAD

**Issue by HemulGM** [eon01/awesome-chatgpt#34]
https://github.com/HemulGM/ChatGPT
https://github.com/HemulGM/DelphiOpenAI

**Comment by eon01** [comment]
Repos added, thanks.

**Comment by HemulGM** [comment]
Pls, add client in "Desktop Apps" section

**Comment by eon01** [comment]
Done. Feel free to open a pull request if you have any updates.
