### ISSUE TITLE
[recommend] GPT-Runner: Conversations with your files! Manage and run your AI presets!

### ISSUE THREAD

**Issue by 2214962083** [eon01/awesome-chatgpt#45]
Github: https://github.com/nicepkg/gpt-runner

<img width="1438" alt="Screenshot 2023-07-15 at 23 22 03" src="https://github.com/eon01/awesome-chatgpt/assets/35005637/bdb898e9-30f2-4d14-949f-8d00ef645122">

**Comment by eon01** [comment]
Added
